const StyleDictionary = require('style-dictionary')
const baseConfig = require('./config.json')

StyleDictionary.registerTransform({
  name: 'size/pixels',
  type: 'value',
  matcher: (token) => {
    return token.attributes.category === 'space'
  },
  transformer: (token) => {
    return `${token.value}px`
  }
})


StyleDictionary.registerFilter({
  name: 'validToken',
  matcher: function (token) {
    return ['dimension', 'string', 'number', 'color'].includes(token.type)
  }
})

StyleDictionary.registerFileHeader({
  name: 'rplHeader',
  fileHeader: (defaultMessage) => {
    return [
      `The values in this file are controlled by the SDP design team.`,
      `Please email design@dpc.vic.gov.au if you wish to modify them.`,
      ``,
      `This file is automatically generated`,
      ...defaultMessage
    ]
  }
})

const StyleDictionaryExtended = StyleDictionary.extend(baseConfig)

StyleDictionaryExtended.buildAllPlatforms()
