const StyleDictionary = require('style-dictionary')
const baseConfig = require('./config.json')
const yaml = require('yaml')

StyleDictionary.registerTransform({
  name: 'size/pixels',
  type: 'value',
  matcher: (token) => {
    return ['sp', 'bp'].includes(token.attributes.category)
  },
  transformer: (token) => {
    return `${token.value}px`
  }
})

StyleDictionary.registerFilter({
  name: 'validToken',
  matcher: function (token) {
    return ['dimension', 'string', 'number', 'color'].includes(token.type)
  }
})

StyleDictionary.registerFilter({
  name: 'isColor',
  matcher: function (token) {
    console.log(token.attributes)
    return token.attributes.category === 'clr'
  }
})

StyleDictionary.registerFileHeader({
  name: 'rplHeader',
  fileHeader: (_defaultMessage) => {
    return [
      `The values in this file are controlled by the SDP design team.`,
      `Please email design@dpc.vic.gov.au if you wish to modify them.`,
      ``,
      `This file is automatically generated, do not edit directly!`
    ]
  }
})

const StyleDictionaryExtended = StyleDictionary.extend({
  ...baseConfig,
  parsers: [
    {
      pattern: /\.yaml$/,
      parse: ({ contents, filePath }) => yaml.parse(contents)
    }
  ]
})

StyleDictionaryExtended.buildAllPlatforms()
