docker-compose-yaml: docker-compose.yml

tasks:
  post-rollout:
    - run:
        name: Post deployed URL to JIRA
        command: |
          if [[ "$LAGOON_PR_HEAD_BRANCH" != "production" ]]; then
            . /app/scripts/jira-post-comment.sh $JIRA_ENDPOINT $JIRA_USERNAME $JIRA_PASSWORD $LAGOON_PR_HEAD_BRANCH $LAGOON_ROUTES "$LAGOON_PR_TITLE"
          fi
        service: app

environments:
  production:
    routes:
      - storybook:
        - "www.ripple.sdp.vic.gov.au":
            tls-acme: 'false'
            insecure: Allow
            hsts: max-age=31536000
  master:
    routes:
      - storybook:
        - "www.master.ripple.sdp.vic.gov.au":
            tls-acme: 'false'
            insecure: Allow
            hsts: max-age=31536000
  develop:
    routes:
      - storybook:
        - "www.develop.ripple.sdp.vic.gov.au":
            tls-acme: 'false'
            insecure: Allow
            hsts: max-age=31536000
