docker-compose-yaml: docker-compose.yml

tasks:
  post-rollout:
    - run:
        name: Post deployed URL to JIRA
        command: |
          if [[ "$LAGOON_PR_HEAD_BRANCH" != "production" ]]; then
            . scripts/jira-post-comment.sh $JIRA_ENDPOINT $JIRA_USERNAME $JIRA_PASSWORD $LAGOON_PR_HEAD_BRANCH $LAGOON_ROUTE "$LAGOON_PR_TITLE"
          fi
        service: app
    - run:
        name: Trigger Nightwatch E2E Tests CI
        command: |-
          . scripts/trigger-e2e.sh
        service: app

environments:
  master:
    routes:
      - app:
          - "www.master.ripple":
              tls-acme: 'false'
              insecure: Allow
              hsts: max-age=31536000
  develop:
    routes:
      - app:
          - "www.develop.ripple":
              tls-acme: 'false'
              insecure: Allow
              hsts: max-age=31536000

  v2:
    routes:
      - app:
          - "www.v2.ripple":
              tls-acme: 'false'
              insecure: Allow
              hsts: max-age=31536000
production_routes:
  active:
    routes:
      - app:
          - www.ripple:
              tls-acme: 'false'
              insecure: Allow
              hsts: max-age=31536000
          - www.active.ripple:
              tls-acme: 'false'
              insecure: Allow
              hsts: max-age=31536000
  standby:
    routes:
      - app:
          - www.inactive.ripple:
              tls-acme: 'false'
              insecure: Allow
              hsts: max-age=31536000