docker-compose-yaml: docker-compose.yml

tasks:
  post-rollout:
    - run:
        name: Post deployed URL to JIRA
        command: |
          if [[ "$LAGOON_PR_HEAD_BRANCH" != "production" ]]; then
            . scripts/jira-post-comment.sh "https://digital-engagement.atlassian.net/" sdp.devs@dpc.vic.gov.au rXSTRbvPf9pkDpnREYrb $LAGOON_GIT_BRANCH sdpa $LAGOON_GIT_BRANCH "$LAGOON_PR_TITLE"
          fi
        service: ripple
