docker-compose-yaml: docker-compose.yml

tasks:
  post-rollout:
    - run:
        name: Post deployed URL to JIRA
        command: |
          if [[ "$LAGOON_PR_HEAD_BRANCH" != "production" ]]; then
            . /app/scripts/jira-post-comment.sh $JIRA_ENDPOINT $JIRA_USERNAME $JIRA_PASSWORD $LAGOON_PR_HEAD_BRANCH $LAGOON_ROUTES "$LAGOON_PR_TITLE"
          fi
        service: app
    - run:
        name: Trigger E2E Tests CI
        command: |-
          . /app/scripts/trigger-e2e.sh
        service: app
