docker-compose-yaml: docker-compose.yml

tasks:
  post-rollout:
    - run:
        name: Post deployed URL to JIRA
        command: |
          if [[ "$LAGOON_PR_HEAD_BRANCH" != "production" ]]; then
            . scripts/jira-post-comment.sh $JIRA_ENDPOINT $JIRA_USERNAME $JIRA_PASSWORD $LAGOON_GIT_BRANCH $LAGOON_GIT_BRANCH "$LAGOON_PR_TITLE"
          fi
        service: storybook

environments:
  master:
    routes:
      - storybook:
        - "www.ripple.sdp.vic.gov.au":
            tls-acme: 'false'
            insecure: Allow
            hsts: max-age=31536000
        - "ripple.sdp.vic.gov.au":
            tls-acme: 'false'
            insecure: Allow
            hsts: max-age=31536000
    monitoring_urls:
      - "ripple.sdp.vic.gov.au"
