docker-compose-yaml: docker-compose.yml

tasks:
  post-rollout:
    - run:
        name: Post deployed URL to JIRA
        command: |
          if [[ "$LAGOON_PR_HEAD_BRANCH" != "production" ]]; then
            . /app/scripts/jira-post-comment.sh $JIRA_ENDPOINT $JIRA_USERNAME $JIRA_PASSWORD $LAGOON_PR_HEAD_BRANCH $LAGOON_ROUTES "$LAGOON_PR_TITLE"
          fi
        service: app
    - run:
        name: Trigger Nightwatch E2E Tests CI
        command: |-
          . /app/scripts/trigger-e2e.sh
        service: app

environments:
  master:
    routes:
      - storybook:
        - "www.ripple.sdp.vic.gov.au":
            tls-acme: 'false'
            insecure: Allow
            hsts: max-age=31536000
      - app:
        - "www.master.reference.sdp.vic.gov.au":
            tls-acme: 'false'
            insecure: Allow
            hsts: max-age=31536000
  develop:
    routes:
      - storybook:
        - "www.develop.ripple.sdp.vic.gov.au":
            tls-acme: 'false'
            insecure: Allow
            hsts: max-age=31536000
      - app:
        - "www.develop.reference.sdp.vic.gov.au":
            tls-acme: 'false'
            insecure: Allow
            hsts: max-age=31536000
  uat:
    routes:
      - storybook:
        - "www.uat.ripple.sdp.vic.gov.au":
            tls-acme: 'false'
            insecure: Allow
            hsts: max-age=31536000
      - app:
        - "www.uat.reference.sdp.vic.gov.au":
            tls-acme: 'false'
            insecure: Allow
            hsts: max-age=31536000
