version: '2'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - LAGOON_GIT_BRANCH=
    networks:
      - default
    labels:
      lagoon.type: node
    environment:
      - AMAZEEIO_URL=www-sdp.docker.internal
      - AMAZEEIO=AMAZEEIO
      - AMAZEEIO_HTTP_PORT=3000
      - BASIC_AUTH=0
    ports:
      - "3000:3000"