version: '2'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.app
      args:
        - LAGOON_GIT_BRANCH=
    networks:
      - default
    labels:
      lagoon.type: node
    environment:
      - AMAZEEIO_URL=vic-gov-au.docker.amazee.io
      - AMAZEEIO=AMAZEEIO
      - AMAZEEIO_HTTP_PORT=3000
      - BASIC_AUTH=0
    ports:
      - "3000:3000"
  storybook:
    build:
      context: .
      dockerfile: Dockerfile.ripple
      args:
        - LAGOON_GIT_BRANCH=
    networks:
      - default
    labels:
      lagoon.type: node
    environment:
      - AMAZEEIO_URL=ripple.docker.amazee.io
      - AMAZEEIO=AMAZEEIO
      - AMAZEEIO_HTTP_PORT=3001
    ports:
      - "3001:3001"
