packages:
  - "packages/**"
  - "examples/**"
  - "docs"
catalog:
  vite: "^6.3.4"
  nuxt: "^3.17.2"
  "@nuxt/kit": "^3.17.2"
  "@nuxt/schema": "^3.17.2"
  cypress: "^13.7.3"
  "cypress-real-events": "^1.14.0"
  vite-svg-loader: "^5.1.0"
  rimraf: "^6.0.1"
  vitest: "^3.2.3"
  "date-fns": "^2.29.3"
onlyBuiltDependencies:
- "@badeball/cypress-cucumber-preprocessor"
- "@parcel/watcher"
- "@swc/core"
- "better-sqlite3"
- "core-js"
- "cypress"
- "esbuild"
- "sharp"
- "swiper"
- "vue-demi"
