packages:
  - "packages/**"
  - "examples/**"
  - "docs"
catalog:
  vite: "^6.3.4"
  nuxt: "^4.2.1"
  "@nuxt/kit": "^4.2.1"
  "@nuxt/schema": "^4.2.1"
  cypress: "^15.7.1"
  "cypress-real-events": "^1.15.0"
  vite-svg-loader: "^5.1.0"
  rimraf: "^6.0.1"
  vitest: "^3.2.3"
  "date-fns": "^2.29.3"
  "@vueuse/core": "^13.9.0"
  "@vueuse/integrations": "^13.9.0"
onlyBuiltDependencies:
- "@badeball/cypress-cucumber-preprocessor"
- "@parcel/watcher"
- "@swc/core"
- "better-sqlite3"
- "core-js"
- "cypress"
- "esbuild"
- "sharp"
- "swiper"
- "vue-demi"
