version: 2.1
parameters:
  e2e:
    type: boolean
    default: false
  e2e_be_url:
    type: string
    default: ''
  e2e_fe_url:
    type: string
    default: ''
  e2e_project:
    type: string
    default: ''

defaults: &defaults
  docker:
    - image: cypress/browsers:node-18.16.0-chrome-114.0.5735.133-1-ff-114.0.2-edge-114.0.1823.51-1
      environment:
        CIRCLE_TEST_REPORTS: test-results
        TZ: "Australia/Melbourne"
      auth:
        username: $DOCKERHUB_USERNAME
        password: $DOCKERHUB_PASSWORD
  working_directory: ~/app

orbs:
  sdp-test: dpc-sdp/sdp-test@2

jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - v8-deps-{{ '{{ checksum "package-lock.json" }}' }}
            - v8-deps-{{ '{{ .Branch }}' }}
            - v8-deps
      - run:
          name: Install Dependencies
          command: npm ci
      - save_cache:
          key: v8-deps-{{ '{{ checksum "package-lock.json" }}' }}
          paths:
            - node_modules
            - ~/.npm
            - ~/.cache
      - run:
          name: build nuxt app
          command: npm run build
      - run:
          name: lint
          command: npm run lint
      - persist_to_workspace:
          root: ~/app
          paths: .

workflows:
  commit:
    when:
      not: << pipeline.parameters.e2e >>
    jobs:
      - build:
          context:
            - dockerhub-readonly
            - Ripple

# This workflow is managed by test automation team
  nightwatch:
    when: << pipeline.parameters.e2e >>
    jobs:
      - sdp-test/smoke-fe:
          filters:
            branches:
              only:
                - v2
          context:
            - e2e-test
          be_url: << pipeline.parameters.e2e_be_url >>
          fe_url: << pipeline.parameters.e2e_fe_url >>
          project: << pipeline.parameters.e2e_project >>
          executor:
            name: sdp-test/e2e
            tag: 2.x
      - sdp-test/e2e-fe-core:
          filters:
            branches:
              only:
                - v2
          requires:
            - sdp-test/smoke-fe
          context:
            - e2e-test
          be_url: << pipeline.parameters.e2e_be_url >>
          fe_url: << pipeline.parameters.e2e_fe_url >>
          project: << pipeline.parameters.e2e_project >>
          executor:
            name: sdp-test/e2e
            tag: 2.x
      - sdp-test/e2e-fe-custom:
          filters:
            branches:
              only:
                - v2
          requires:
            - sdp-test/smoke-fe
          context:
            - e2e-test
          be_url: << pipeline.parameters.e2e_be_url >>
          fe_url: << pipeline.parameters.e2e_fe_url >>
          project: << pipeline.parameters.e2e_project >>
          executor:
            name: sdp-test/e2e
            tag: 2.x
      - hold-visualtest:
          type: approval
          requires:
            - sdp-test/smoke-fe
      - sdp-test/e2e-fe-core-visual:
          filters:
            branches:
              only:
                - v2
          requires:
            - sdp-test/smoke-fe
            - hold-visualtest
          context:
            - e2e-test
          be_url: << pipeline.parameters.e2e_be_url >>
          fe_url: << pipeline.parameters.e2e_fe_url >>
          project: << pipeline.parameters.e2e_project >>
          executor:
            name: sdp-test/e2e
            tag: 2.x
      - sdp-test/e2e-fe-custom-visual:
          filters:
            branches:
              only:
                - v2
          requires:
            - hold-visualtest
            - sdp-test/smoke-fe
          context:
            - e2e-test
          be_url: << pipeline.parameters.e2e_be_url >>
          fe_url: << pipeline.parameters.e2e_fe_url >>
          project: << pipeline.parameters.e2e_project >>
          executor:
            name: sdp-test/e2e
            tag: 2.x