openapi: 3.0.0
info:
  description: Tide API for Ripple SDP projects
  version: 2.0.0
  title: Tide Ripple API
  contact:
    email: dylan.kelly@dpc.vic.gov.au
servers:
  - url: http://localhost:{port}/tide-api/{version}
    description: Local development server
    variables:
      port:
        default: '3000'
      version:
        default: v2
        enum:
          - v2
  - url: '{protocol}://{environment}.{project}.vic.gov.au/tide-api/{version}'
    description: 'Section.io CDN hosted'
    variables:
      protocol:
        enum:
          - http
          - https
        default: https
      version:
        default: v2
        enum:
          - v2
      environment:
        default: develop
        enum:
          - develop
          - production
          - prod-left
          - master
      project:
        default: together
        description: Project hostname
  - url: '{protocol}://app.{environment}.{project}.sdp1.sdp.vic.gov.au/tide-api/{version}'
    description: 'PR Environments'
    variables:
      protocol:
        enum:
          - http
          - https
        default: https
      version:
        default: v2
        enum:
          - v2
      environment:
        default: develop
      project:
        default: virtual-vic-gov-au
        description: Project hostname
paths:
  /page:
    get:
      summary: Tide page
      description: Tide page response
      parameters:
        - name: path
          schema:
            type: string
          in: query
          required: true
          example: /
          allowReserved: true
        - name: site
          schema:
            type: integer
          in: query
          required: false
          example: 4
      responses:
        '200':
          description: Tide Page response
          content:
            application/json:
              schema:
                oneOf:
                  - $ref: '#/components/schemas/landing_page'
                discriminator:
                  propertyName: type
        '400':
          description: bad input parameter
          content:
            application/json:
              schema:
                oneOf:
                  - $ref: '#/components/schemas/Error'
        '404':
          description: page not fond
          content:
            application/json:
              schema:
                oneOf:
                  - $ref: '#/components/schemas/Error'
        '500':
          description: page not fond
          content:
            application/json:
              schema:
                oneOf:
                  - $ref: '#/components/schemas/Error'

  /site/{siteid}:
    get:
      summary: Site information
      description: Includes menus
      parameters:
        - name: siteid
          in: path
          schema:
            type: integer
          required: true
          example: 4
      responses:
        '200':
          description: Tide Site response
          content:
            application/json:
              schema:
                type: object
                required:
                  - name
                properties: {}
        '400':
          description: bad input parameter
  /schema:
    get:
      summary: Open API 3.0 schema
      responses:
        '200':
          description: Open API 3.0 schema response
          content:
            application/json:
              schema:
                type: object
  /docs:
    get:
      summary: API documentation
      responses:
        '200':
          description: Swagger UI documentation
components:
  schemas:
    Error:
      type: object
      properties:
        error:
          type: boolean
        status:
          type: number
        message:
          type: string
    TidePage:
      type: object
      required:
        - nid
        - title
        - changed
        - created
      properties:
        nid:
          type: integer
          example: 123
        title:
          type: string
          example: Demo landing page
        changed:
          type: string
          format: date-time
          example: '2016-08-29T09:12:33.001Z'
        created:
          type: string
          format: date-time
          example: '2016-08-29T09:12:33.001Z'
