import type { Metadata } from 'next'
import '@dpc-sdp/ripple-ui-styles/global'
import { RplIconSprite, RplLayout } from '@dpc-sdp/ripple-ui-react'
import SiteAlert from './components/SiteAlert'
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html>
      <body>
        <RplLayout>
          <RplLayout.AboveHeader>
            <SiteAlert id='test' message='test'></SiteAlert>
          </RplLayout.AboveHeader>

          <RplLayout.Header>HEADER</RplLayout.Header>

          <RplLayout.Breadcrumbs></RplLayout.Breadcrumbs>

          <RplLayout.AboveBody></RplLayout.AboveBody>

          <RplLayout.Body>{children}</RplLayout.Body>

          <RplLayout.Sidebar></RplLayout.Sidebar>

          <RplLayout.BelowBody></RplLayout.BelowBody>

          <RplLayout.Footer>FOOTER</RplLayout.Footer>
        </RplLayout>
      </body>
    </html>
  )
}
