export default {
  'icon-accessible': () => import('./custom/icon-accessible.svg?component'),
  'icon-add': () => import('./custom/icon-add.svg?component'),
  'icon-arrow-down': () => import('./custom/icon-arrow-down.svg?component'),
  'icon-arrow-left': () => import('./custom/icon-arrow-left.svg?component'),
  'icon-arrow-right': () => import('./custom/icon-arrow-right.svg?component'),
  'icon-arrow-up': () => import('./custom/icon-arrow-up.svg?component'),
  'icon-attach': () => import('./custom/icon-attach.svg?component'),
  'icon-browser': () => import('./custom/icon-browser.svg?component'),
  'icon-calendar-lined': () =>
    import('./custom/icon-calendar-lined.svg?component'),
  'icon-cancel-circle-filled': () =>
    import('./custom/icon-cancel-circle-filled.svg?component'),
  'icon-car': () => import('./custom/icon-car.svg?component'),
  'icon-check': () => import('./custom/icon-check.svg?component'),
  'icon-child-lined': () => import('./custom/icon-child-lined.svg?component'),
  'icon-dollar-circle-filled': () =>
    import('./custom/icon-dollar-circle-filled.svg?component'),
  'icon-fire': () => import('./custom/icon-fire.svg?component'),
  'icon-flood': () => import('./custom/icon-flood.svg?component'),
  'icon-free': () => import('./custom/icon-free.svg?component'),
  'icon-instagram': () => import('./custom/icon-instagram.svg?component'),
  'icon-lightning': () => import('./custom/icon-lightning.svg?component'),
  'icon-link': () => import('./custom/icon-link.svg?component'),
  'icon-list': () => import('./custom/icon-list.svg?component'),
  'icon-loading': () => import('./custom/icon-loading.svg?component'),
  'icon-log-in-lined': () => import('./custom/icon-log-in-lined.svg?component'),
  'icon-mail-lined': () => import('./custom/icon-mail-lined.svg?component'),
  'icon-medical': () => import('./custom/icon-medical.svg?component'),
  'icon-menu': () => import('./custom/icon-menu.svg?component'),
  'icon-microphone': () => import('./custom/icon-microphone.svg?component'),
  'icon-pause-circle-lined': () =>
    import('./custom/icon-pause-circle-lined.svg?component'),
  'icon-person': () => import('./custom/icon-person.svg?component'),
  'icon-play-circle-lined': () =>
    import('./custom/icon-play-circle-lined.svg?component'),
  'icon-print-lined': () => import('./custom/icon-print-lined.svg?component'),
  'icon-question-circle-lined': () =>
    import('./custom/icon-question-circle-lined.svg?component'),
  'icon-search': () => import('./custom/icon-search.svg?component'),
  'icon-senior': () => import('./custom/icon-senior.svg?component'),
  'icon-share': () => import('./custom/icon-share.svg?component'),
  'icon-smoke': () => import('./custom/icon-smoke.svg?component'),
  'icon-spotify': () => import('./custom/icon-spotify.svg?component'),
  'icon-star': () => import('./custom/icon-star.svg?component'),
  'icon-stop-circle-lined': () =>
    import('./custom/icon-stop-circle-lined.svg?component'),
  'icon-table-lined': () => import('./custom/icon-table-lined.svg?component'),
  'icon-temperature': () => import('./custom/icon-temperature.svg?component'),
  'icon-traffic': () => import('./custom/icon-traffic.svg?component'),
  'icon-trash-lined': () => import('./custom/icon-trash-lined.svg?component'),
  'icon-upload': () => import('./custom/icon-upload.svg?component'),
  'icon-user-circle-filled': () =>
    import('./custom/icon-user-circle-filled.svg?component'),
  'icon-video': () => import('./custom/icon-video.svg?component'),
  'icon-wechat': () => import('./custom/icon-wechat.svg?component'),
  'icon-youtube': () => import('./custom/icon-youtube.svg?component'),
  'icon-zoom-in': () => import('./custom/icon-zoom-in.svg?component'),
  'icon-zoom-out': () => import('./custom/icon-zoom-out.svg?component')
}
