name: dpc-sdp/ripple/commit
on:
  workflow_call:
  push:
    branches-ignore:
      - master
env:
  CHROMATIC_APP_CODE: ${{ secrets.CHROMATIC_APP_CODE }}
jobs:
  build:
    uses: ./.github/workflows/build.yml
  test:
    needs:
      - build
    uses: ./.github/workflows/test.yml
  storybook:
    runs-on: ubuntu-latest
    needs:
    - build
    steps:
    - uses: actions/checkout@v3.5.0
      with:
        fetch-depth: 0 # 👈 Required to retrieve git history
    - uses: actions/setup-node@v3.6.0
      with:
        node-version: '14'
    - name: Restore cache
      uses: actions/cache@v3.3.1
      with:
        key: v10-deps-${{ hashFiles('yarn.lock') }}
        path: | 
          ./.cache
          **/node_modules
    - name: Run UI test
      run: cd src && yarn chromatic --project-token $CHROMATIC_APP_CODE --exit-zero-on-changes  