name: dpc-sdp/ripple/e2e
on:
  workflow_dispatch:
    inputs:
      project:
        type: string
        required: true
      be_url:
        type: string
      fe_url:
        type: string
jobs:
  e2e_be:
    uses: dpc-sdp/github-actions/.github/workflows/run_e2e_be.yml@main
    secrets: inherit
    with:
      tags: "(@core or @${{ inputs.project }}) and @regression"
      be_url: ${{ inputs.be_url }}
      project: ${{ inputs.project }}
      browser: 'chrome'
      test_id: 'fixture'
      test_type: ':e2e:'
      runner: 'ubuntu-latest'
  e2e_fe_smoke:
    uses: dpc-sdp/github-actions/.github/workflows/run_e2e_fe.yml@main
    secrets: inherit
    with:
      tags: "(@smoke and @core) or (@smoke and @${{ inputs.project }})"
      be_url: ${{ inputs.be_url }}
      fe_url: ${{ inputs.fe_url }}
      project: ${{ inputs.project }}
      browser: 'chrome'
      test_id: 'fixture'
      test_type: ':e2e:'
      runner: 'ubuntu-latest'
  e2e_fe_chrome:
    needs:
      - e2e_be
      - e2e_fe_smoke
    uses: dpc-sdp/github-actions/.github/workflows/run_e2e_fe.yml@main
    secrets: inherit
    with:
      tags: "(@core or @${{ inputs.project }}) and @regression and not @mobile"
      be_url: ${{ inputs.be_url }}
      fe_url: ${{ inputs.fe_url }}
      project: ${{ inputs.project }}
      browser: 'chrome'
      test_id: 'fixture'
      test_type: ':e2e:'
      runner: 'ubuntu-latest'
  e2e_fe_android:
    needs:
      - e2e_be
      - e2e_fe_smoke
    uses: dpc-sdp/github-actions/.github/workflows/run_e2e_fe.yml@main
    secrets: inherit
    with:
      tags: "(@core or @${{ inputs.project }}) and @regression and not @desktop"
      be_url: ${{ inputs.be_url }}
      fe_url: ${{ inputs.fe_url }}
      project: ${{ inputs.project }}
      browser: 'androidChrome'
      test_id: 'fixture'
      test_type: ':e2e:'
      runner: 'ubuntu-latest'
  set_status:
    needs: [e2e_be, e2e_fe_smoke, e2e_fe_chrome, e2e_fe_android]
    if: ${{ always() }}
    uses: dpc-sdp/github-actions/.github/workflows/set_status.yml@feature/DEVOPS-252-tide
    secrets: inherit
    with:
      context: 'e2e'
      description: 'Ripple E2E testing'
      target_url: ${{ github.event.repository.html_url }}/actions/runs/${{ github.run_id }}