name: dpc-sdp/ripple/e2e
on:
  workflow_dispatch:
    inputs:
      project:
        type: string
        required: true
      be_url:
        type: string
        required: true
      fe_url:
        type: string
        required: true

jobs:
  fe_smoke:
    uses: dpc-sdp/github-actions/.github/workflows/run_e2e_fe.yml@main
    secrets: inherit
    with:
      name: 'FE smoke'
      tags: "@core and @smoke"
      fe_url: ${{ inputs.fe_url }}
      be_url: ${{ inputs.be_url }}
      project: ${{ inputs.project }}
      test_type: ":smoke-test:"
      test_id: "fixture"
      parallel: 10
      tag: 'sdp-dev-r1-chrome'
  fe_core:
    needs: fe_smoke
    uses: dpc-sdp/github-actions/.github/workflows/run_e2e_fe.yml@main
    secrets: inherit
    with:
      name: 'FE core'
      tags: "@core and @regression and not @mobile"
      fe_url: ${{ inputs.fe_url }}
      be_url: ${{ inputs.be_url }}
      project: ${{ inputs.project }}
      test_id: "fixture"
      parallel: 10
      test_type: ':e2e:'
      tag: 'sdp-dev-r1-chrome'
  fe_core_safari:
    needs: fe_smoke
    uses: dpc-sdp/github-actions/.github/workflows/run_e2e_fe.yml@main
    secrets: inherit
    with:
      name: 'FE Core Safari'
      tags: '@core and @regression and not @mobile'
      fe_url: ${{ inputs.fe_url }}
      be_url: ${{ inputs.be_url }}
      project: ${{ inputs.project }}
      test_id: "fixture"
      parallel: 1
      tag: 'sdp-dev-chrome'
      browser: 'browserstack.safari'
  fe_core_android_chrome:
    needs: fe_smoke
    uses: dpc-sdp/github-actions/.github/workflows/run_e2e_fe.yml@main
    secrets: inherit
    with:
      name: 'FE Core Safari'
      tags: '@core and @regression and not @desktop'
      fe_url: ${{ inputs.fe_url }}
      be_url: ${{ inputs.be_url }}
      project: ${{ inputs.project }}
      test_id: "fixture"
      parallel: 1
      tag: 'sdp-dev-r1-chrome'
      browser: 'browserstack.androidChrome'
  fe_core_iphone_safari:
    needs: fe_smoke
    uses: dpc-sdp/github-actions/.github/workflows/run_e2e_fe.yml@main
    secrets: inherit
    with:
      name: 'FE Core Safari'
      tags: '@core and @regression and not @desktop'
      fe_url: ${{ inputs.fe_url }}
      be_url: ${{ inputs.be_url }}
      project: ${{ inputs.project }}
      test_id: "fixture"
      parallel: 1
      tag: 'sdp-dev-r1-chrome'
      browser: 'browserstack.iphoneSafari'
  fe_core_visual:
    needs: fe_smoke
    uses: dpc-sdp/github-actions/.github/workflows/run_e2e_fe.yml@main
    secrets: inherit
    with:
      name: 'FE core visual'
      app: frontend-visual
      tags: "@core and @visual-regression-minimal"
      fe_url: ${{ inputs.fe_url }}
      be_url: ${{ inputs.be_url }}
      project: ${{ inputs.project }}
      test_type: ":applitools:"
      test_id: "fixture"
      parallel: 1
      tag: 'sdp-dev-r1-chrome'
      browser: 'chrome'
      eyes_appname: 'sdp-core-v1'
  set_status:
    needs: [fe_core, fe_core_safari, fe_core_iphone_safari, fe_core_android_chrome, fe_core_visual]
    if: ${{ always() }}
    uses: dpc-sdp/github-actions/.github/workflows/set_status.yml@main
    secrets: inherit
    with:
      context: 'e2e'
      description: 'Ripple E2E testing'
      target_url: ${{ github.event.repository.html_url }}/actions/runs/${{ github.run_id }}
