name: dpc-sdp/ripple/nightwatch
on:
  workflow_dispatch:
    inputs:
      project:
        type: string
        required: true
      be_url:
        type: string
      fe_url:
        type: string
jobs:
  e2e_be:
    uses: dpc-sdp/github-actions/.github/workflows/run_e2e_be.yml@main
    secrets: inherit
    with:
      tags: "(@core or @${{ inputs.project }}) and @regression"
      be_url: ${{ inputs.be_url }}
      project: ${{ inputs.project }}
      browser: 'chrome'
      test_id: 'fixture'
      test_type: ':nightwatch:'
      runner: 'ubuntu-latest'
  e2e_fe_smoke:
    uses: dpc-sdp/github-actions/.github/workflows/run_e2e_fe.yml@main
    secrets: inherit
    with:
      tags: "(@smoke and @core) or (@smoke and @${{ inputs.project }})"
      be_url: ${{ inputs.be_url }}
      fe_url: ${{ inputs.fe_url }}
      project: ${{ inputs.project }}
      browser: 'chrome'
      test_id: 'fixture'
      test_type: ':nightwatch:'
      runner: 'ubuntu-latest'
  e2e_fe_chrome:
    needs:
      - e2e_be
      - e2e_fe_smoke
    uses: dpc-sdp/github-actions/.github/workflows/run_e2e_fe.yml@main
    secrets: inherit
    with:
      tags: "(@core or @${{ inputs.project }}) and @regression and not @mobile"
      be_url: ${{ inputs.be_url }}
      fe_url: ${{ inputs.fe_url }}
      project: ${{ inputs.project }}
      browser: 'chrome'
      test_id: 'fixture'
      test_type: ':nightwatch:'
      runner: 'ubuntu-latest'
  e2e_fe_android:
    needs:
      - e2e_be
      - e2e_fe_smoke
    uses: dpc-sdp/github-actions/.github/workflows/run_e2e_fe.yml@main
    secrets: inherit
    with:
      tags: "(@core or @${{ inputs.project }}) and @regression and not @desktop"
      be_url: ${{ inputs.be_url }}
      fe_url: ${{ inputs.fe_url }}
      project: ${{ inputs.project }}
      browser: 'androidChrome'
      test_id: 'fixture'
      test_type: ':nightwatch:'
      runner: 'ubuntu-latest'
  set_status:
    runs-on: ubuntu-latest
    needs: [e2e_be, e2e_fe_smoke, e2e_fe_chrome, e2e_fe_android]
    if: ${{ always() }}
    steps:
      - name: Set e2e job status
        uses: dpc-sdp/github-actions/.github/workflows/set_status.yml@feature/DEVOPS-252-tide
        with:
          context: 'e2e_be: ${{ needs.e2e_be.outputs.status }}'
          description: 'Backend E2E testing'
      - name: Set e2e_fe_smoke job status
        uses: dpc-sdp/github-actions/.github/workflows/set_status.yml@feature/DEVOPS-252-tide
        with:
          context: 'e2e_fe_smoke: ${{ needs.e2e_be.e2e_fe_smoke.status }}'
          description: 'Frontend E2E smoke testing'
      - name: Set e2e_fe_chrome job status
        uses: dpc-sdp/github-actions/.github/workflows/set_status.yml@feature/DEVOPS-252-tide
        with:
          context: 'e2e_fe_chrome: ${{ needs.e2e_be.e2e_fe_chrome.status }}'
          description: 'Frontend E2E chrome testing'
      - name: Set e2e_fe_android job status
        uses: dpc-sdp/github-actions/.github/workflows/set_status.yml@feature/DEVOPS-252-tide
        with:
          context: 'e2e_fe_android: ${{ needs.e2e_be.e2e_fe_android.status }}'
          description: 'Frontend E2E android testing'