name: dpc-sdp/ripple/publish-to-npm
on:
  push:
    branches:
      # Uncomment below once testing has been completed and we are ready to publish using this workflow
      #- master
      - 'github-action/disable-workflow'
jobs:
  build:
    uses: ./.github/workflows/build.yml
  test:
    needs:
      - build
    uses: ./.github/workflows/test.yml
  confirm-release:
    environment:
      name: approval
    runs-on: ubuntu-latest
    needs:
    - test
    steps:
    - run: echo 'approved'
  create-release:
    needs:
    - confirm-release
    uses: ./.github/workflows/create-release.yml
  tag-release:
    needs:
    - create-release
    permissions:
      contents: write
    uses: ./.github/workflows/tag-release.yml
  create-release-notes:
    runs-on: ubuntu-latest
    needs:
    - tag-release
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v3.5.0
    - name: Restore cache
      uses: actions/cache@v3.3.1
      with:
        key: v10-deps-${{ hashFiles('yarn.lock') }}
        path: | 
          ./.cache
          **/node_modules
    - name: Install github-release-notes package
      run: yarn add -D -W github-release-notes
    - name: Generate release notes and publish to GitHub
      run: |-
        PACKAGE_VERSION=$(node -pe "require('./lerna.json')['version']")
        npx gren release --data-source=commits --tags=v$PACKAGE_VERSION --override --token ${{ secrets.GITHUB_TOKEN }}
