name: dpc-sdp/ripple/tag-release
on:
  workflow_call:
jobs:
  tag-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v3.5.0
    - name: Git tag the release with the `lerna.json` version number
      run: |-
        PACKAGE_VERSION=$(node -pe "require('./lerna.json')['version']")
        git tag v$PACKAGE_VERSION
    - name: Push git tag to the remote repository
      run: |-
        PACKAGE_VERSION=$(node -pe "require('./lerna.json')['version']")
        echo $PACKAGE_VERSION
        git push -q https://${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git v$PACKAGE_VERSION